// <auto-generated />
using System;
using System.Text.Json;
using KEGEstation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KEGEstation.Infrastructure.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KEGEstation.Domain.Kim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("UnlockCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unlock_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_kims_creator_id");

                    b.ToTable("kims", (string)null);
                });

            modelBuilder.Entity("KEGEstation.Domain.KimTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<JsonElement>("Answer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<short>("AnswerColumnsSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("answer_columns_size");

                    b.Property<short>("AnswerRowsSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("answer_rows_size");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string>("FileS3Keys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("file_s3_keys")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.PrimitiveCollection<string>("ImageS3Keys")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("image_s3_keys")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<long>("KimId")
                        .HasColumnType("bigint")
                        .HasColumnName("kim_id");

                    b.Property<short?>("Number")
                        .HasColumnType("smallint")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.HasIndex("KimId")
                        .HasDatabaseName("ix_kim_tasks_kim_id");

                    b.ToTable("kim_tasks", (string)null);
                });

            modelBuilder.Entity("KEGEstation.Domain.Result", b =>
                {
                    b.Property<long>("KimId")
                        .HasColumnType("bigint")
                        .HasColumnName("kim_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonElement?>("Metadata")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<short>("ResultValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("result");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("KimId", "UserId");

                    b.HasIndex("KimId")
                        .HasDatabaseName("ix_kim_results_kim_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_kim_results_user_id");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("KEGEstation.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<JsonElement>("Contacts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("contacts")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("STUDENT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_first_name");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KEGEstation.Domain.Kim", b =>
                {
                    b.HasOne("KEGEstation.Domain.User", "Creator")
                        .WithMany("CreatedKims")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("KEGEstation.Domain.KimTask", b =>
                {
                    b.HasOne("KEGEstation.Domain.Kim", "Kim")
                        .WithMany("Tasks")
                        .HasForeignKey("KimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kim");
                });

            modelBuilder.Entity("KEGEstation.Domain.Result", b =>
                {
                    b.HasOne("KEGEstation.Domain.Kim", "Kim")
                        .WithMany("Results")
                        .HasForeignKey("KimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KEGEstation.Domain.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KEGEstation.Domain.Kim", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("KEGEstation.Domain.User", b =>
                {
                    b.Navigation("CreatedKims");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
